### ISSUE TITLE
Make new PR for "BEP-0013.md - update annotation handling"

### ISSUE THREAD

**Issue by cthoyt** [vtoure/MICAST#15]
William accidentally deleted the [pull request](https://github.com/belbio/bep/pull/34) made by @vtoure for the updates that enabled the final compliance of BEL with MI2CAST.

@vtoure would you please make a new PR with the same stuff? I don't think there's a way to resurrect them

**Comment by vtoure** [comment]
The new pull request has been sent: https://github.com/belbio/bep/pull/36.
