### ISSUE TITLE
Make source and target entity types explicit

### ISSUE THREAD

**Issue by cthoyt** [vtoure/MICAST#9]
It's often not obvious if the source or target entity type is a gene, transcript, or protein. With the exception of the situations where an entity type-specific database like ensembl or uniprot is used, gene nomenclature databases are quite callously used to describe transcripts and proteins without clear indication of which entity type is actually meant (though sometimes it's possible to infer from the relations used)

At the cost of verbosity, I would suggest including a source entity type and target entity type column in the MI2CAST. Maybe the systems biology ontology (SBO) would be the place to go to get a controlled vocabulary for entity types

**Comment by vtoure** [comment]
We have '[biological type](https://github.com/MI2CAST/MI2CAST/blob/master/docs/MI2CAST_guideline.md#biological-type)' that is intended for this. Currently, MI2CAST recommends to annotate this information when the used identifier does not correspond to the intended type of entity. 
The CV suggested is MI - branch [interactor type](https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0313) which contains entity types.

We can add a sentence about the specific case you mention (ambiguous type of entity from database) in the 'biological type' - I think it fits well there. Would be good to provide database names. Any suggestions? HGNC?

**Comment by vtoure** [comment]
Fixed in https://github.com/MI2CAST/MI2CAST/commit/3ffd1b4f8a5276880cd389d2b46c3ab881346b8a
